name: ðŸž Bug Report
title: "Bug: "
description: This form is to report unexpected behavior in react-semantic-flex.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your precious time to file an issue!
        ðŸ™ We are sorry for the inconvenience this issue has caused you and want to resolve it as soon as possible.

        Help us help you! We know that your time is precious and hate to ask for any more of it, but the first step in fixing this issue is to understand the issue.
        Taking some extra time to ensure that we are able to reproduce the issue will help us significantly in resolving the issue.
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Which package version is causing the problem?
    validations:
      required: true
  - type: checkboxes
    id: browser
    attributes:
      label: Web Browser
      description: What Browser are you using?
      options:
        - label: Chrome (only supported)
        - label: Safari
        - label: Firefox
        - label: Other (Please specify)
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: Which Browser version is causing the problem?
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using?
      options:
        - label: macOS
        - label: Linux
        - label: Windows
        - label: Other (Please specify)
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What is the behavior that currently you experience?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What is the behavior that you expect to happen?
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: GitHub Repo
      description: |
        This is extremely important! Please do take a few minutes of your time to create a repo to help us reproduce the issue.
        This is the best way to help us reproduce the issue and fix it as soon as possible.
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide some instructions to reproduce the issue in the repo provided above. Be as detailed as possible.
      value: |
        1.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Failure Logs
      description: Please include any relevant log snippets or files here. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Is there any additional information that you can provide?
  - type: markdown
    attributes:
      value: |
        > If we are not able to reproduce the issue, we will likely prioritize fixing other issues we can reproduce. Please do your best to fill out all of the sections above.
